version: "3.9"

services:
  rabbitmq:
    image: "rabbitmq:3.12-management"
    container_name: eliza-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=eliza
      - RABBITMQ_DEFAULT_PASS=eliza123
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 6
    networks:
      - eliza-network

  eliza-app:
    build:
      context: ../py-app
      dockerfile: ../docker-app/Dockerfile
    container_name: eliza-app
    ports:
      - "8000:8000"
    volumes:
      - ../py-app/config:/app/config
      - ../py-app/storage:/app/storage
    environment:
      - CLTL_LOGGING_CONFIG=/app/config/logging.config
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - eliza-network

volumes:
  rabbitmq_data:

networks:
  eliza-network:
    driver: bridge
