services:
  rabbitmq:
    image: "rabbitmq:3.12-management"
    container_name: cltl-llm-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=cltl
      - RABBITMQ_DEFAULT_PASS=cltl123
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 6
    networks:
      - cltl-llm-network

  ollama: &ollama
    build:
      context: .
      dockerfile: ollama.Dockerfile
#    profiles: ["server"]
    ports:
      - "11434:11434"
    healthcheck:
      test: [ "CMD", "curl", "ollama:11434" ]
      interval: 10s
      timeout: 10s
      retries: 600
    networks:
      - cltl-llm-network
#
#  ollama-gpu:
#    <<: *ollama
#    profiles: ["server-gpu"]
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [gpu]

  pull-model:
    build:
      context: .
      dockerfile: ./pull_model.Dockerfile
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - LLM=llama3.2
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - cltl-llm-network

  cltl-llm-app:
    build:
      context: ../py-app
      dockerfile: ../docker-app/Dockerfile
    container_name: cltl-llm-app
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ../py-app/storage:/app/storage
    environment:
      - CLTL_LOGGING_CONFIG=/app/config/logging.config
    depends_on:
      rabbitmq:
        condition: service_healthy
      pull-model:
        condition: service_completed_successfully
    networks:
      - cltl-llm-network
    extra_hosts:
      # On Linux, map the special name to the host gateway.
      # On Mac/Windows it's already defined; this line is harmless there.
      - "host.docker.internal:host-gateway"

volumes:
  rabbitmq_data:

networks:
  cltl-llm-network:
    driver: bridge
